[project]
name = "musializer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ffmpeg>=1.4",
    "librosa>=0.11.0",
    "pyaudio>=0.2.14",
    "pygame-ce>=2.5.6",
    "pyqt5>=5.15.11",
]
